name: CI/CD Pipeline

# 1. ТРИГЕРИ (Коли запускається pipeline)
on:
  push:
    branches:
      - main # Автоматично при пуші в main
      - dev  # Автоматично при пуші в dev
  workflow_dispatch: # Дозволяє запустити процес вручну через кнопку в GitHub

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_API: soniklvl/autoparts-api
  IMAGE_NAME_WEB: soniklvl/autoparts-web

jobs:
  # Тестування та Компіляція 
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Тестування Бекенду
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Build .NET
        run: dotnet build ./AutopartsShop/AutopartsShop.csproj -c Release
      # unit-тести:
      # - name: Test .NET
      #   run: dotnet test ./AutopartsShop/AutopartsShop.csproj --no-build

      # Тестування Фронтенду
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install JS Dependencies
        working-directory: ./vite
        run: npm ci
      - name: Build React App (Check for compilation errors)
        working-directory: ./vite
        run: npm run build

  # Створення Docker образів і пуш в GHCR
  build-and-push-images:
    needs: test-and-build 
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: ./AutopartsShop
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_API }}:${{ github.ref_name }}
      
      - name: Create frontend .env file
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "VITE_API_URL=http://${{ secrets.PROD_HOST }}/api/analytics" > ./vite/.env
          else
            echo "VITE_API_URL=http://${{ secrets.DEV_HOST }}:5005/api/analytics" > ./vite/.env
          fi

      - name: Build and push WEB image
        uses: docker/build-push-action@v5
        with:
          context: ./vite
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_WEB }}:${{ github.ref_name }}

  # Розгортання (Droplet для Dev, Kubernetes для Main)
  deploy:
    needs: build-and-push-images
    runs-on: ubuntu-latest
    steps:
      # --- ЛОГІКА ДЛЯ DEV-ГІЛКИ (Старий Droplet) ---
      - name: Deploy DEV via SSH
        if: github.ref_name == 'dev'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          envs: GITHUB_REF_NAME
          script: |
            echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            mkdir -p ~/autoparts-dev && cd ~/autoparts-dev
            export IMAGE_TAG=${GITHUB_REF_NAME}
            docker compose pull
            docker compose up -d

      # --- ЛОГІКА ДЛЯ MAIN-ГІЛКИ (Kubernetes) ---
      - name: Install doctl (for K8s)
        if: github.ref_name == 'main'
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_PAT }}

      - name: Deploy PROD to Kubernetes
        if: github.ref_name == 'main'
        run: |
          doctl kubernetes cluster kubeconfig save autoparts-k8s
          
          kubectl rollout restart deployment autoparts-web
          kubectl rollout restart deployment autoparts-api
          kubectl rollout status deployment/autoparts-web
          kubectl rollout status deployment/autoparts-api